In [1]:
import pandas as pd
Path=r'C:\Users\sanab\Desktop\pandas\Superstore.xlsx'
Path

'C:\\Users\\sanab\\Desktop\\pandas\\Superstore.xlsx'

In [5]:
orders=pd.read_excel(Path)
orders

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Dispatch Time,Unnamed: 22,Descrete,quantity,dispatch time
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2,NaN,NaN,NaN,NaN
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2,NaN,NaN,NaN,NaN
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,3,NaN,NaN,NaN,NaN
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,6,NaN,NaN,NaN,NaN
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,6,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,1,NaN,NaN,NaN,NaN
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,4,NaN,NaN,NaN,NaN
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,4,NaN,NaN,NaN,NaN
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,4,NaN,NaN,NaN,NaN
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,5,NaN,NaN,NaN,NaN

# GROUP BY

In [4]:
orders.groupby('Region').agg({'Sales' : 'sum'})

               Sales
Region
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245

In [ ]:
#multiple aggregations
orders.groupby('Region').agg({'Sales':'sum','Profit':'sum'})

               Sales       Profit
Region
Central  501239.8908   39706.3625
East     678781.2400   91522.7800
South    391721.9050   46749.4303
West     725457.8245  108418.4489

In [ ]:
#multiple group by
orders.groupby(['Region','State']).agg({'Sales':'sum','Profit':'sum'})

                                    Sales      Profit
Region  State
Central Illinois               80166.1010 -12607.8870
        Indiana                53555.3600  18382.9363
        Iowa                    4579.7600   1183.8119
        Kansas                  2914.3100    836.4435
        Michigan               76269.6140  24463.1876
        Minnesota              29863.1500  10823.1874
        Missouri               22205.1500   6436.2105
        Nebraska                7464.9300   2037.0942
        North Dakota             919.9100    230.1497
        Oklahoma               19683.3900   4853.9560
        South Dakota            1315.5600    394.8283
        Texas                 170188.0458 -25729.3563
        Wisconsin              32114.6100   8401.8004
East    Connecticut            13384.3570   3511.4918
        Delaware               27451.0690   9977.3748
        District of Columbia    2865.0200   1059.5893
        Maine                   1270.5300    454.4862
        Maryland               23705.5230   7031.1788
        Massachusetts          28634.4340   6785.5016
        New Hampshire           7292.5240   1706.5028
        New Jersey             35764.3120   9772.9138
        New York              310876.2710  74038.5486
        Ohio                   78258.1360 -16971.3766
        Pennsylvania          116511.9140 -15559.9603
        Rhode Island           22627.9560   7285.6293
        Vermont                 8929.3700   2244.9783
        West Virginia           1209.8240    185.9216
South   Alabama                19510.6400   5786.8253
        Arkansas               11678.1300   4008.6871
        Florida                89473.7080  -3399.3017
        Georgia                49095.8400  16250.0433
        Kentucky               36591.7500  11199.6966
        Louisiana               9217.0300   2196.1023
        Mississippi            10771.3400   3172.9762
        North Carolina         55603.1640  -7490.9122
        South Carolina          8481.7100   1769.0566
        Tennessee              30661.8730  -5341.6936
        Virginia               70636.7200  18597.9504
West    Arizona                35282.0010  -3427.9246
        California            457687.6315  76381.3871
        Colorado               32108.1180  -6527.8579
        Idaho                   4382.4860    826.7231
        Montana                 5589.3520   1833.3285
        Nevada                 16729.1020   3316.7659
        New Mexico              4783.5220   1157.1161
        Oregon                 17431.1500  -1190.4705
        Utah                   11220.0560   2546.5335
        Washington            138641.2700  33402.6517
        Wyoming                 1603.1360    100.1960

In [11]:
#find out top 3 state having highest profit
orders.groupby('State').agg({'Profit':'sum'}).sort_values('Profit',ascending=False).head(3)

                Profit
State
California  76381.3871
New York    74038.5486
Washington  33402.6517

# CROSS TABULATION

In [14]:
pd.crosstab(orders['Region'],orders['Category'])

Category  Furniture  Office Supplies  Technology
Region
Central         481             1422         420
East            601             1712         535
South           332              995         293
West            707             1897         599

# PIVOT TABLES

In [15]:
pd.pivot_table(orders,index='Region',columns='Category',values='Sales',aggfunc='sum')

Category    Furniture  Office Supplies  Technology
Region
Central   163797.1638       167026.415  170416.312
East      208291.2040       205516.055  264973.981
South     117298.6840       125651.313  148771.908
West      252612.7435       220853.249  251991.832

In [17]:
web=pd.DataFrame({'OrderID':[1,7,4] , 'Sales' : [213,4,54]})
web

   OrderID  Sales
0        1    213
1        7      4
2        4     54

In [20]:
app=pd.DataFrame({'OrderID':[2,3,5,6] , 'Sales' : [334,45,98,67]})
app

   OrderID  Sales
0        2    334
1        3     45
2        5     98
3        6     67

# CONCATENATION

In [ ]:
pd.concat([web,app],axis=0)  #row wise

   OrderID  Sales
0        1    213
1        7      4
2        4     54
0        2    334
1        3     45
2        5     98
3        6     67

In [ ]:
pd.concat([web,app],axis=1)  #col wise

   OrderID  Sales  OrderID  Sales
0      1.0  213.0        2    334
1      7.0    4.0        3     45
2      4.0   54.0        5     98
3      NaN    NaN        6     67

# JOINS

In [23]:
cust=pd.DataFrame({'cust_id':[1,2,3,4,5],'cust_name':['raam','shyam','hari','murli','krishna']})
cust

   cust_id cust_name
0        1      raam
1        2     shyam
2        3      hari
3        4     murli
4        5   krishna

In [25]:
bill=pd.DataFrame({'order_id':[11,22,33,44,55],'cust_id':[1,1,2,3,6],'product':['lap','mouse','keyboard','console','monitor']})
bill

   order_id  cust_id   product
0        11        1       lap
1        22        1     mouse
2        33        2  keyboard
3        44        3   console
4        55        6   monitor

In [ ]:
#matching from both table

pd.merge(cust,bill,on='cust_id',how='inner')

   cust_id cust_name  order_id   product
0        1      raam        11       lap
1        1      raam        22     mouse
2        2     shyam        33  keyboard
3        3      hari        44   console

In [ ]:
#all from right table and matching from right table

pd.merge(cust,bill,on='cust_id',how='left')

   cust_id cust_name  order_id   product
0        1      raam      11.0       lap
1        1      raam      22.0     mouse
2        2     shyam      33.0  keyboard
3        3      hari      44.0   console
4        4     murli       NaN       NaN
5        5   krishna       NaN       NaN

In [ ]:
#all from right table and matching from left table

pd.merge(cust,bill,on='cust_id',how='right')

   cust_id cust_name  order_id   product
0        1      raam        11       lap
1        1      raam        22     mouse
2        2     shyam        33  keyboard
3        3      hari        44   console
4        6       NaN        55   monitor

In [ ]:
#all data from both table

pd.merge(cust,bill,on='cust_id',how='outer')

   cust_id cust_name  order_id   product
0        1      raam      11.0       lap
1        1      raam      22.0     mouse
2        2     shyam      33.0  keyboard
3        3      hari      44.0   console
4        4     murli       NaN       NaN
5        5   krishna       NaN       NaN
6        6       NaN      55.0   monitor

In [32]:
df=pd.pivot_table(orders,index='Region',columns='Category',values='Sales',aggfunc='sum').reset_index()
df

Category   Region    Furniture  Office Supplies  Technology
0         Central  163797.1638       167026.415  170416.312
1            East  208291.2040       205516.055  264973.981
2           South  117298.6840       125651.313  148771.908
3            West  252612.7435       220853.249  251991.832